name: ServiceNow GitHub Actions Demo

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish from Dev
    runs-on: ubuntu-latest

    steps:
      - name: ServiceNow CI/CD Apply Changes
        uses: ServiceNow/sncicd-apply-changes@2.0.0
        env:
          nowUsername: admin
          nowPassword: DHR@9Ksajd8!
          nowSourceInstance: https://dev186230.service-now.com/
          appSysID: 8459695447b63110202ea09f016d43ab

      - name: ServiceNow CI/CD Publish App
        id: publish_app
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.1
          versionFormat: template
        env:
          nowUsername: admin
          nowPassword: DHR@9Ksajd8!
          nowSourceInstance: https://dev186230.service-now.com/
          appSysID: 8459695447b63110202ea09f016d43ab
          
    outputs:
      publishversion: ${{ steps.publish_app.outputs.newVersion }}

  apply-changes:
    name: Apply Changes to Install Instance
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: ServiceNow CI/CD Apply Changes to Install Instance
        uses: ServiceNow/sncicd-apply-changes@2.0.0
        env:
          nowUsername: admin
          nowPassword: DHR@9Ksajd8!
          nowSourceInstance: https://dev186230.service-now.com/
          nowInstallInstance: https://dev186741.service-now.com/
          appSysID: 8459695447b63110202ea09f016d43ab
